// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testSquareArrayU8RHelper {
  static encode(message: testSquareArrayU8RHelper, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.value);
  }

  static decode(reader: Reader, length: i32): testSquareArrayU8RHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testSquareArrayU8RHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Uint8Array;

  constructor(value: Uint8Array = new Uint8Array(0)) {
    this.value = value;
  }
}

export function encodetestSquareArrayU8RHelper(
  message: testSquareArrayU8RHelper
): Uint8Array {
  return Protobuf.encode(message, testSquareArrayU8RHelper.encode);
}

export function decodetestSquareArrayU8RHelper(
  buffer: Uint8Array
): testSquareArrayU8RHelper {
  return Protobuf.decode<testSquareArrayU8RHelper>(
    buffer,
    testSquareArrayU8RHelper.decode
  );
}
