// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class test6RHelper {
  static encode(message: test6RHelper, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.value);
  }

  static decode(reader: Reader, length: i32): test6RHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new test6RHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: string;

  constructor(value = "") {
    this.value = value;
  }
}

export function encodetest6RHelper(message: test6RHelper): Uint8Array {
  return Protobuf.encode(message, test6RHelper.encode);
}

export function decodetest6RHelper(buffer: Uint8Array): test6RHelper {
  return Protobuf.decode<test6RHelper>(buffer, test6RHelper.decode);
}
