// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testArrayI32RetRHelper {
  static encode(message: testArrayI32RetRHelper, writer: Writer): void {
    const value = message.value;
    if (value.length !== 0) {
      for (let i: i32 = 0; i < value.length; ++i) {
        writer.uint32(8);
        writer.int32(value[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testArrayI32RetRHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testArrayI32RetRHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value.push(reader.int32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Array<i32>;

  constructor(value: Array<i32> = []) {
    this.value = value;
  }
}

export function encodetestArrayI32RetRHelper(
  message: testArrayI32RetRHelper
): Uint8Array {
  return Protobuf.encode(message, testArrayI32RetRHelper.encode);
}

export function decodetestArrayI32RetRHelper(
  buffer: Uint8Array
): testArrayI32RetRHelper {
  return Protobuf.decode<testArrayI32RetRHelper>(
    buffer,
    testArrayI32RetRHelper.decode
  );
}
