// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testArrayOfUint64ArrayRHelper {
  static encode(message: testArrayOfUint64ArrayRHelper, writer: Writer): void {
    const value = message.value;
    if (value.length !== 0) {
      for (let i: i32 = 0; i < value.length; ++i) {
        writer.uint32(8);
        writer.uint64(value[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testArrayOfUint64ArrayRHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testArrayOfUint64ArrayRHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value.push(reader.uint64());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Array<u64>;

  constructor(value: Array<u64> = []) {
    this.value = value;
  }
}

export function encodetestArrayOfUint64ArrayRHelper(
  message: testArrayOfUint64ArrayRHelper
): Uint8Array {
  return Protobuf.encode(message, testArrayOfUint64ArrayRHelper.encode);
}

export function decodetestArrayOfUint64ArrayRHelper(
  buffer: Uint8Array
): testArrayOfUint64ArrayRHelper {
  return Protobuf.decode<testArrayOfUint64ArrayRHelper>(
    buffer,
    testArrayOfUint64ArrayRHelper.decode
  );
}
