// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testSquareArrayU8Helper {
  static encode(message: testSquareArrayU8Helper, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.arg1);
  }

  static decode(reader: Reader, length: i32): testSquareArrayU8Helper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testSquareArrayU8Helper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1 = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Uint8Array;

  constructor(arg1: Uint8Array = new Uint8Array(0)) {
    this.arg1 = arg1;
  }
}

export function encodetestSquareArrayU8Helper(
  message: testSquareArrayU8Helper
): Uint8Array {
  return Protobuf.encode(message, testSquareArrayU8Helper.encode);
}

export function decodetestSquareArrayU8Helper(
  buffer: Uint8Array
): testSquareArrayU8Helper {
  return Protobuf.decode<testSquareArrayU8Helper>(
    buffer,
    testSquareArrayU8Helper.decode
  );
}
