// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testSquareArrayStringHelper {
  static encode(message: testSquareArrayStringHelper, writer: Writer): void {
    const arg1 = message.arg1;
    if (arg1.length !== 0) {
      for (let i: i32 = 0; i < arg1.length; ++i) {
        writer.uint32(10);
        writer.string(arg1[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testSquareArrayStringHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testSquareArrayStringHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Array<string>;

  constructor(arg1: Array<string> = []) {
    this.arg1 = arg1;
  }
}

export function encodetestSquareArrayStringHelper(
  message: testSquareArrayStringHelper
): Uint8Array {
  return Protobuf.encode(message, testSquareArrayStringHelper.encode);
}

export function decodetestSquareArrayStringHelper(
  buffer: Uint8Array
): testSquareArrayStringHelper {
  return Protobuf.decode<testSquareArrayStringHelper>(
    buffer,
    testSquareArrayStringHelper.decode
  );
}
