// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testArrayI64RHelper {
  static encode(message: testArrayI64RHelper, writer: Writer): void {
    const value = message.value;
    if (value.length !== 0) {
      for (let i: i32 = 0; i < value.length; ++i) {
        writer.uint32(8);
        writer.int64(value[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testArrayI64RHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testArrayI64RHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value.push(reader.int64());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Array<i64>;

  constructor(value: Array<i64> = []) {
    this.value = value;
  }
}

export function encodetestArrayI64RHelper(
  message: testArrayI64RHelper
): Uint8Array {
  return Protobuf.encode(message, testArrayI64RHelper.encode);
}

export function decodetestArrayI64RHelper(
  buffer: Uint8Array
): testArrayI64RHelper {
  return Protobuf.decode<testArrayI64RHelper>(
    buffer,
    testArrayI64RHelper.decode
  );
}
