// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testSquareArrayU128Helper {
  static encode(message: testSquareArrayU128Helper, writer: Writer): void {
    const arg1 = message.arg1;
    if (arg1.length !== 0) {
      for (let i: i32 = 0; i < arg1.length; ++i) {
        writer.uint32(10);
        writer.bytes(arg1[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testSquareArrayU128Helper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testSquareArrayU128Helper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Array<Uint8Array>;

  constructor(arg1: Array<Uint8Array> = []) {
    this.arg1 = arg1;
  }
}

export function encodetestSquareArrayU128Helper(
  message: testSquareArrayU128Helper
): Uint8Array {
  return Protobuf.encode(message, testSquareArrayU128Helper.encode);
}

export function decodetestSquareArrayU128Helper(
  buffer: Uint8Array
): testSquareArrayU128Helper {
  return Protobuf.decode<testSquareArrayU128Helper>(
    buffer,
    testSquareArrayU128Helper.decode
  );
}
