// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testInt8ArrayRHelper {
  static encode(message: testInt8ArrayRHelper, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.value);
  }

  static decode(reader: Reader, length: i32): testInt8ArrayRHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testInt8ArrayRHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Uint8Array;

  constructor(value: Uint8Array = new Uint8Array(0)) {
    this.value = value;
  }
}

export function encodetestInt8ArrayRHelper(
  message: testInt8ArrayRHelper
): Uint8Array {
  return Protobuf.encode(message, testInt8ArrayRHelper.encode);
}

export function decodetestInt8ArrayRHelper(
  buffer: Uint8Array
): testInt8ArrayRHelper {
  return Protobuf.decode<testInt8ArrayRHelper>(
    buffer,
    testInt8ArrayRHelper.decode
  );
}
