// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testArrayStringRHelper {
  static encode(message: testArrayStringRHelper, writer: Writer): void {
    const value = message.value;
    if (value.length !== 0) {
      for (let i: i32 = 0; i < value.length; ++i) {
        writer.uint32(10);
        writer.string(value[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testArrayStringRHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testArrayStringRHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Array<string>;

  constructor(value: Array<string> = []) {
    this.value = value;
  }
}

export function encodetestArrayStringRHelper(
  message: testArrayStringRHelper
): Uint8Array {
  return Protobuf.encode(message, testArrayStringRHelper.encode);
}

export function decodetestArrayStringRHelper(
  buffer: Uint8Array
): testArrayStringRHelper {
  return Protobuf.decode<testArrayStringRHelper>(
    buffer,
    testArrayStringRHelper.decode
  );
}
