// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class test3Helper {
  static encode(message: test3Helper, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.arg);
  }

  static decode(reader: Reader, length: i32): test3Helper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new test3Helper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg: Uint8Array;

  constructor(arg: Uint8Array = new Uint8Array(0)) {
    this.arg = arg;
  }
}

export function encodetest3Helper(message: test3Helper): Uint8Array {
  return Protobuf.encode(message, test3Helper.encode);
}

export function decodetest3Helper(buffer: Uint8Array): test3Helper {
  return Protobuf.decode<test3Helper>(buffer, test3Helper.decode);
}
