// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testInt64ArrayHelper {
  static encode(message: testInt64ArrayHelper, writer: Writer): void {
    const arg1 = message.arg1;
    if (arg1.length !== 0) {
      for (let i: i32 = 0; i < arg1.length; ++i) {
        writer.uint32(8);
        writer.int64(arg1[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testInt64ArrayHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testInt64ArrayHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1.push(reader.int64());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Array<i64>;

  constructor(arg1: Array<i64> = []) {
    this.arg1 = arg1;
  }
}

export function encodetestInt64ArrayHelper(
  message: testInt64ArrayHelper
): Uint8Array {
  return Protobuf.encode(message, testInt64ArrayHelper.encode);
}

export function decodetestInt64ArrayHelper(
  buffer: Uint8Array
): testInt64ArrayHelper {
  return Protobuf.decode<testInt64ArrayHelper>(
    buffer,
    testInt64ArrayHelper.decode
  );
}
