// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class test5Helper {
  static encode(message: test5Helper, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.arg1);

    writer.uint32(16);
    writer.int32(message.arg2);
  }

  static decode(reader: Reader, length: i32): test5Helper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new test5Helper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1 = reader.int32();
          break;

        case 2:
          message.arg2 = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: i32;
  arg2: i32;

  constructor(arg1: i32 = 0, arg2: i32 = 0) {
    this.arg1 = arg1;
    this.arg2 = arg2;
  }
}

export function encodetest5Helper(message: test5Helper): Uint8Array {
  return Protobuf.encode(message, test5Helper.encode);
}

export function decodetest5Helper(buffer: Uint8Array): test5Helper {
  return Protobuf.decode<test5Helper>(buffer, test5Helper.decode);
}
