// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testArrayBoolHelper {
  static encode(message: testArrayBoolHelper, writer: Writer): void {
    const arg1 = message.arg1;
    if (arg1.length !== 0) {
      for (let i: i32 = 0; i < arg1.length; ++i) {
        writer.uint32(8);
        writer.bool(arg1[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testArrayBoolHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testArrayBoolHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1.push(reader.bool());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Array<bool>;

  constructor(arg1: Array<bool> = []) {
    this.arg1 = arg1;
  }
}

export function encodetestArrayBoolHelper(
  message: testArrayBoolHelper
): Uint8Array {
  return Protobuf.encode(message, testArrayBoolHelper.encode);
}

export function decodetestArrayBoolHelper(
  buffer: Uint8Array
): testArrayBoolHelper {
  return Protobuf.decode<testArrayBoolHelper>(
    buffer,
    testArrayBoolHelper.decode
  );
}
