// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testUint64ArrayRHelper {
  static encode(message: testUint64ArrayRHelper, writer: Writer): void {
    const value = message.value;
    if (value.length !== 0) {
      for (let i: i32 = 0; i < value.length; ++i) {
        writer.uint32(8);
        writer.uint64(value[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testUint64ArrayRHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testUint64ArrayRHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value.push(reader.uint64());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Array<u64>;

  constructor(value: Array<u64> = []) {
    this.value = value;
  }
}

export function encodetestUint64ArrayRHelper(
  message: testUint64ArrayRHelper
): Uint8Array {
  return Protobuf.encode(message, testUint64ArrayRHelper.encode);
}

export function decodetestUint64ArrayRHelper(
  buffer: Uint8Array
): testUint64ArrayRHelper {
  return Protobuf.decode<testUint64ArrayRHelper>(
    buffer,
    testUint64ArrayRHelper.decode
  );
}
