// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testUint16ArrayRHelper {
  static encode(message: testUint16ArrayRHelper, writer: Writer): void {
    const value = message.value;
    if (value.length !== 0) {
      for (let i: i32 = 0; i < value.length; ++i) {
        writer.uint32(8);
        writer.uint32(value[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testUint16ArrayRHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testUint16ArrayRHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value.push(reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Array<u32>;

  constructor(value: Array<u32> = []) {
    this.value = value;
  }
}

export function encodetestUint16ArrayRHelper(
  message: testUint16ArrayRHelper
): Uint8Array {
  return Protobuf.encode(message, testUint16ArrayRHelper.encode);
}

export function decodetestUint16ArrayRHelper(
  buffer: Uint8Array
): testUint16ArrayRHelper {
  return Protobuf.decode<testUint16ArrayRHelper>(
    buffer,
    testUint16ArrayRHelper.decode
  );
}
