// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testArrayBoolRHelper {
  static encode(message: testArrayBoolRHelper, writer: Writer): void {
    const value = message.value;
    if (value.length !== 0) {
      for (let i: i32 = 0; i < value.length; ++i) {
        writer.uint32(8);
        writer.bool(value[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testArrayBoolRHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testArrayBoolRHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value.push(reader.bool());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Array<bool>;

  constructor(value: Array<bool> = []) {
    this.value = value;
  }
}

export function encodetestArrayBoolRHelper(
  message: testArrayBoolRHelper
): Uint8Array {
  return Protobuf.encode(message, testArrayBoolRHelper.encode);
}

export function decodetestArrayBoolRHelper(
  buffer: Uint8Array
): testArrayBoolRHelper {
  return Protobuf.decode<testArrayBoolRHelper>(
    buffer,
    testArrayBoolRHelper.decode
  );
}
