// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testArrayU8Helper {
  static encode(message: testArrayU8Helper, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.arg1);
  }

  static decode(reader: Reader, length: i32): testArrayU8Helper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testArrayU8Helper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1 = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Uint8Array;

  constructor(arg1: Uint8Array = new Uint8Array(0)) {
    this.arg1 = arg1;
  }
}

export function encodetestArrayU8Helper(
  message: testArrayU8Helper
): Uint8Array {
  return Protobuf.encode(message, testArrayU8Helper.encode);
}

export function decodetestArrayU8Helper(buffer: Uint8Array): testArrayU8Helper {
  return Protobuf.decode<testArrayU8Helper>(buffer, testArrayU8Helper.decode);
}
