// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testBoolHelper {
  static encode(message: testBoolHelper, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.arg1);
  }

  static decode(reader: Reader, length: i32): testBoolHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testBoolHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1 = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: bool;

  constructor(arg1: bool = false) {
    this.arg1 = arg1;
  }
}

export function encodetestBoolHelper(message: testBoolHelper): Uint8Array {
  return Protobuf.encode(message, testBoolHelper.encode);
}

export function decodetestBoolHelper(buffer: Uint8Array): testBoolHelper {
  return Protobuf.decode<testBoolHelper>(buffer, testBoolHelper.decode);
}
