// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testInt8ArrayHelper {
  static encode(message: testInt8ArrayHelper, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.arg1);
  }

  static decode(reader: Reader, length: i32): testInt8ArrayHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testInt8ArrayHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1 = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Uint8Array;

  constructor(arg1: Uint8Array = new Uint8Array(0)) {
    this.arg1 = arg1;
  }
}

export function encodetestInt8ArrayHelper(
  message: testInt8ArrayHelper
): Uint8Array {
  return Protobuf.encode(message, testInt8ArrayHelper.encode);
}

export function decodetestInt8ArrayHelper(
  buffer: Uint8Array
): testInt8ArrayHelper {
  return Protobuf.decode<testInt8ArrayHelper>(
    buffer,
    testInt8ArrayHelper.decode
  );
}
