// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testSquareArrayOfInt32ArrayHelper {
  static encode(
    message: testSquareArrayOfInt32ArrayHelper,
    writer: Writer
  ): void {
    const arg1 = message.arg1;
    if (arg1.length !== 0) {
      for (let i: i32 = 0; i < arg1.length; ++i) {
        writer.uint32(8);
        writer.int32(arg1[i]);
      }
    }
  }

  static decode(
    reader: Reader,
    length: i32
  ): testSquareArrayOfInt32ArrayHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testSquareArrayOfInt32ArrayHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1.push(reader.int32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Array<i32>;

  constructor(arg1: Array<i32> = []) {
    this.arg1 = arg1;
  }
}

export function encodetestSquareArrayOfInt32ArrayHelper(
  message: testSquareArrayOfInt32ArrayHelper
): Uint8Array {
  return Protobuf.encode(message, testSquareArrayOfInt32ArrayHelper.encode);
}

export function decodetestSquareArrayOfInt32ArrayHelper(
  buffer: Uint8Array
): testSquareArrayOfInt32ArrayHelper {
  return Protobuf.decode<testSquareArrayOfInt32ArrayHelper>(
    buffer,
    testSquareArrayOfInt32ArrayHelper.decode
  );
}
