// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testSquareArrayU128RHelper {
  static encode(message: testSquareArrayU128RHelper, writer: Writer): void {
    const value = message.value;
    if (value.length !== 0) {
      for (let i: i32 = 0; i < value.length; ++i) {
        writer.uint32(10);
        writer.bytes(value[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testSquareArrayU128RHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testSquareArrayU128RHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Array<Uint8Array>;

  constructor(value: Array<Uint8Array> = []) {
    this.value = value;
  }
}

export function encodetestSquareArrayU128RHelper(
  message: testSquareArrayU128RHelper
): Uint8Array {
  return Protobuf.encode(message, testSquareArrayU128RHelper.encode);
}

export function decodetestSquareArrayU128RHelper(
  buffer: Uint8Array
): testSquareArrayU128RHelper {
  return Protobuf.decode<testSquareArrayU128RHelper>(
    buffer,
    testSquareArrayU128RHelper.decode
  );
}
