// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testBoolRHelper {
  static encode(message: testBoolRHelper, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.value);
  }

  static decode(reader: Reader, length: i32): testBoolRHelper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testBoolRHelper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: bool;

  constructor(value: bool = false) {
    this.value = value;
  }
}

export function encodetestBoolRHelper(message: testBoolRHelper): Uint8Array {
  return Protobuf.encode(message, testBoolRHelper.encode);
}

export function decodetestBoolRHelper(buffer: Uint8Array): testBoolRHelper {
  return Protobuf.decode<testBoolRHelper>(buffer, testBoolRHelper.decode);
}
