// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testArrayU64Helper {
  static encode(message: testArrayU64Helper, writer: Writer): void {
    const arg1 = message.arg1;
    if (arg1.length !== 0) {
      for (let i: i32 = 0; i < arg1.length; ++i) {
        writer.uint32(8);
        writer.uint64(arg1[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testArrayU64Helper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testArrayU64Helper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1.push(reader.uint64());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Array<u64>;

  constructor(arg1: Array<u64> = []) {
    this.arg1 = arg1;
  }
}

export function encodetestArrayU64Helper(
  message: testArrayU64Helper
): Uint8Array {
  return Protobuf.encode(message, testArrayU64Helper.encode);
}

export function decodetestArrayU64Helper(
  buffer: Uint8Array
): testArrayU64Helper {
  return Protobuf.decode<testArrayU64Helper>(buffer, testArrayU64Helper.decode);
}
