// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testArrayI8Helper {
  static encode(message: testArrayI8Helper, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.arg1);
  }

  static decode(reader: Reader, length: i32): testArrayI8Helper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testArrayI8Helper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1 = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Uint8Array;

  constructor(arg1: Uint8Array = new Uint8Array(0)) {
    this.arg1 = arg1;
  }
}

export function encodetestArrayI8Helper(
  message: testArrayI8Helper
): Uint8Array {
  return Protobuf.encode(message, testArrayI8Helper.encode);
}

export function decodetestArrayI8Helper(buffer: Uint8Array): testArrayI8Helper {
  return Protobuf.decode<testArrayI8Helper>(buffer, testArrayI8Helper.decode);
}
