// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class testArrayI64Helper {
  static encode(message: testArrayI64Helper, writer: Writer): void {
    const arg1 = message.arg1;
    if (arg1.length !== 0) {
      for (let i: i32 = 0; i < arg1.length; ++i) {
        writer.uint32(8);
        writer.int64(arg1[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): testArrayI64Helper {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new testArrayI64Helper();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.arg1.push(reader.int64());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  arg1: Array<i64>;

  constructor(arg1: Array<i64> = []) {
    this.arg1 = arg1;
  }
}

export function encodetestArrayI64Helper(
  message: testArrayI64Helper
): Uint8Array {
  return Protobuf.encode(message, testArrayI64Helper.encode);
}

export function decodetestArrayI64Helper(
  buffer: Uint8Array
): testArrayI64Helper {
  return Protobuf.decode<testArrayI64Helper>(buffer, testArrayI64Helper.decode);
}
