// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Annotation } from "./GeneratedCodeInfo/Annotation";

export class GeneratedCodeInfo {
  static encode(message: GeneratedCodeInfo, writer: Writer): void {
    const annotation = message.annotation;
    for (let i: i32 = 0; i < annotation.length; ++i) {
      writer.uint32(10);
      writer.fork();
      Annotation.encode(annotation[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): GeneratedCodeInfo {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GeneratedCodeInfo();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.annotation.push(Annotation.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  annotation: Array<Annotation>;

  constructor(annotation: Array<Annotation> = []) {
    this.annotation = annotation;
  }
}

export function encodeGeneratedCodeInfo(
  message: GeneratedCodeInfo
): Uint8Array {
  return Protobuf.encode(message, GeneratedCodeInfo.encode);
}

export function decodeGeneratedCodeInfo(buffer: Uint8Array): GeneratedCodeInfo {
  return Protobuf.decode<GeneratedCodeInfo>(buffer, GeneratedCodeInfo.decode);
}
