// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { UninterpretedOption } from "./UninterpretedOption";
import { IdempotencyLevel } from "./MethodOptions/IdempotencyLevel";

export class MethodOptions {
  static encode(message: MethodOptions, writer: Writer): void {
    writer.uint32(264);
    writer.bool(message.deprecated);

    writer.uint32(272);
    writer.int32(message.idempotencyLevel);

    const uninterpretedOption = message.uninterpretedOption;
    for (let i: i32 = 0; i < uninterpretedOption.length; ++i) {
      writer.uint32(7994);
      writer.fork();
      UninterpretedOption.encode(uninterpretedOption[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MethodOptions {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MethodOptions();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 33:
          message.deprecated = reader.bool();
          break;

        case 34:
          message.idempotencyLevel = reader.int32();
          break;

        case 999:
          message.uninterpretedOption.push(
            UninterpretedOption.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  deprecated: bool;
  idempotencyLevel: IdempotencyLevel;
  uninterpretedOption: Array<UninterpretedOption>;

  constructor(
    deprecated: bool = false,
    idempotencyLevel: IdempotencyLevel = IdempotencyLevel.IDEMPOTENCY_UNKNOWN,
    uninterpretedOption: Array<UninterpretedOption> = []
  ) {
    this.deprecated = deprecated;
    this.idempotencyLevel = idempotencyLevel;
    this.uninterpretedOption = uninterpretedOption;
  }
}

export function encodeMethodOptions(message: MethodOptions): Uint8Array {
  return Protobuf.encode(message, MethodOptions.encode);
}

export function decodeMethodOptions(buffer: Uint8Array): MethodOptions {
  return Protobuf.decode<MethodOptions>(buffer, MethodOptions.decode);
}
