// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { OneofOptions } from "./OneofOptions";

export class OneofDescriptorProto {
  static encode(message: OneofDescriptorProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.name);

    const options = message.options;
    if (options !== null) {
      writer.uint32(18);
      writer.fork();
      OneofOptions.encode(options, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): OneofDescriptorProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new OneofDescriptorProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.name = reader.string();
          break;

        case 2:
          message.options = OneofOptions.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  name: string;
  options: OneofOptions | null;

  constructor(name = "", options: OneofOptions | null = null) {
    this.name = name;
    this.options = options;
  }
}

export function encodeOneofDescriptorProto(
  message: OneofDescriptorProto
): Uint8Array {
  return Protobuf.encode(message, OneofDescriptorProto.encode);
}

export function decodeOneofDescriptorProto(
  buffer: Uint8Array
): OneofDescriptorProto {
  return Protobuf.decode<OneofDescriptorProto>(
    buffer,
    OneofDescriptorProto.decode
  );
}
