name: Unit tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: run test
      run: |
        npm ci
        npm run build
        npm run fmt:check
        npm run test:ci
    - id: coverage
      run: |
        value=$(npm run test:ci | grep -oE '^│\s*total\s+\│\s*([0-9.]+)%' | grep -oE '[0-9]+(\.[0-9]+)?%' | cut -d'.' -f1)
        echo "coverage=$value" >> $GITHUB_OUTPUT

    - name: Add test coverage to README
      run:  ${GITHUB_WORKSPACE}/.github/coverage.sh
      shell: bash

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Generate coverage badge"
        file_pattern: "README.md"
        # Commit code using massabot account that can bypass push and MR restriction
        commit_author: massabot <info@massa.net>
 
      env:
        COVERAGE: ${{ steps.coverage.outputs.coverage }}
