name: Publish NPM Packages

on:
  push:
  # release:
  #   types: [ created ]

jobs:
  test:
    uses: ./.github/workflows/node.js.yml

  # publish-npm:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         registry-url: https://registry.npmjs.org/
  #     - name: publish
  #       run: |
  #         npm pkg delete scripts.prepare
  #         npm ci
  #         npm run build
  #         npm publish --ws --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  deploy-typedoc:
    strategy:
      matrix:
        packageName: [as-proba,as-transformer,as-types] 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Generate doc
      run: |
        npm ci
        npm run doc
        mv packages/${{ matrix.packageName }}/docs/${{ matrix.packageName }}/html ${{ matrix.packageName }}
    - name: Deploy files
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.MASSANET_HOST }}
        USERNAME: ${{ secrets.MASSANET_USERNAME }}
        KEY: ${{ secrets.MASSANET_SSHKEY }}
      with:
        source: "./${{ matrix.packageName}}"
        target: "/var/www/type-doc"

