name: Generate Powered-By
on:
  pull_request_target: 
    types: [assigned, unassigned]

jobs:
  generate-powered:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        # Checkout code using massabot account
        token: ${{ secrets.MASSABOTCLASSIC }}

    - name: Install node 
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org

    - name: Install license-report and jq
      run: |
        sudo apt-get update -y && sudo apt-get install -y jq
        sudo npm install -g license-report

    - name: Install project dependencies
      run: |
        npm ci

    - name: Generate Powered-By for 'as-types'
      run: cd packages/as-types && npm i && ./../../generate_powered-by.sh && cd ../../

    - name: Generate Powered-By for 'as-proba'
      run: cd packages/as-proba && npm i && ./../../generate_powered-by.sh && cd ../../

    - name: Generate Powered-By for 'as-transformer'
      run: cd packages/as-transformer && npm i && ./../../generate_powered-by.sh && cd ../../

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Generate powered-by"
        file_pattern: "**/powered-by.md"
        # Commit code using massabot account that can bypass push and MR restriction
        commit_author: massabot <info@massa.net>