name: Move PR Request
on:
  pull_request:
    types: [review_requested]

jobs:
  move-card-to-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-number: 13
          column-name: PR
          issue-number: ${{ github.event.pull_request.number }}
