name: Publish NPM Packages & Deploy Docs

on:
  release:
    types: [ published ]

jobs:
  test:
    uses: ./.github/workflows/unit-test.yml

  publish-npm:
    needs: test

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Publish on npm
        run: |
          npm pkg delete scripts.prepare
          npm ci
          npm run build
          npm publish --ws --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

  deploy-typedoc:
    needs: test

    strategy:
      matrix:
        packageName: [as-proba,as-transformer,as-types]
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Generate doc
      run: |
        npm ci
        npm run doc --workspace packages/${{ matrix.packageName }}
        mv packages/${{ matrix.packageName }}/docs/${{ matrix.packageName }}/html ${{ matrix.packageName }}
 
    - name: Deploy files
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.MASSANET_HOST }}
        USERNAME: ${{ secrets.MASSANET_USERNAME }}
        KEY: ${{ secrets.MASSANET_SSHKEY }}
      with:
        source: "./${{ matrix.packageName}}"
        target: "/var/www/type-doc"
