name: Publish NPM Packages & Deploy Docs

on:
  release:
    types: [ published ]

jobs:
  deploy-typedoc:

    strategy:
      matrix:
        packageName: [as-proba,as-transformer,as-types]
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Generate doc
      run: |
        npm ci
        npm run doc --workspace packages/${{ matrix.packageName }}
        mv packages/${{ matrix.packageName }}/docs/${{ matrix.packageName }}/html ${{ matrix.packageName }}
 
    - name: Deploy files
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.MASSANET_HOST }}
        USERNAME: ${{ secrets.MASSANET_USERNAME }}
        KEY: ${{ secrets.MASSANET_SSHKEY }}
        source: "./${{ matrix.packageName}}"
        target: "/var/www/type-doc"
